/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.escuelaing.ieti.lab1.microservicio;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class MicroservicioApplicationTests {

    @Test
    void contextLoads() {
    }

}
